repos:
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black
    args: [--line-length=79]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-case-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.2
  hooks:
  - id: autopep8
    args:
    - --in-place
    - --max-line-length=79

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args:
    - --max-line-length=120

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
    exclude: poetry.lock
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.35.0
  hooks:
  - id: markdownlint
    args: [--fix]

- repo: https://github.com/python-poetry/poetry
  rev: 1.5.1    # add version here
  hooks:
  - id: poetry-check
  - id: poetry-lock