version: '3.8'
services:
  backend:
    build: ./lingua-backend
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    ports:
    - 5000:5000
    env_file:
    - production.env

  frontend:
    build:
      context: ./lingua-frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
    - 3000:80
    env_file:
    - production.env
